{% set name = "setupmeta" %}
{% set version = "2.7.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ffc9bf2c6fb89fe0e1ba2e22c45789ac2443084006e00d01ed68b034f663360c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - setuptools

test:
  imports:
    - setupmeta

about:
  home: https://github.com/zsimic/setupmeta
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simplify your setup.py
  description: |
    Writing a setup.py typically involves lots of boilerplate and copy-pasting from project to project.
    This package aims to simplify that and bring some DRY principle to python packaging. For more
    information and examples, please refer to: https://github.com/zsimic/setupmeta.
    This package is only required to enable the building of Conda Python packages that
    make use of setupmeta (which is otherwise ordinarily installed dynamically
    as part of the setup.py workflows).
  doc_url: https://github.com/zsimic/setupmeta
  dev_url: https://github.com/zsimic/setupmeta

extra:
  recipe-maintainers:
    - zsimic
    - matthewwardrop
